/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: af09cda75189a1012674ea2274f38d47)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/entry");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
